name: mak_b
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fancy_bottom_navigation: ^0.3.3
  flutter_svg: ^0.23.0+1
  motion_tab_bar_v2: ^0.2.5
  font_awesome_flutter: ^9.2.0
  flutter_image_slideshow: ^0.1.1
  device_preview: ^0.8.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0
  #  flutter_sslcommerze: ^1.0.1-nullsafety.0
  fluttertoast: ^8.0.8
  flutter_sslcommerz: ^2.0.0-nullsafety.0
  video_player: ^2.2.6
  get: ^4.3.8
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+4
  firebase_storage: ^10.0.6
  flutter_staggered_grid_view: ^0.4.1
  dependencies:
  carousel_pro_nullsafety: ^1.0.2
  platform_device_id: ^1.0.1
  intl: ^0.17.0

#flutter_shimmer: ^2.1.1


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/deub.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-Light.ttf
          weight: 300
        - asset: fonts/ZillaSlab-SemiBold.ttf
          weight: 500
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
